HW7
watchbot23/GDM.UIP.HW pull request #7
Opened 2019-01-31 16:15 UTC by watchbot23

2019-01-31 20:07 UTC, LiDmYr requested changes
Надо работать

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Models/LogRecord.cs
> +        public static int Id { get; set; }
какой-то треш. Открытый на запись статический айдишник...

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Models/LogRecord.cs
> +            return $"{Id++}, {DateTime.ToString()}, {LogLevel}, {Message}";
если я для одного инстанса `LogRecord `вызвову 100 раз `ToString().`...какой-то треш...

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/SquareCalculator.cs
> +                long res = CalculateArea(points, true);
`CalculateArea(points, true)` - ты это уже считал выше...зачем еще раз делаешь?

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +        SquareCalculator calc = new SquareCalculator();
класс `InputCoordinates` имеет проперт `SquareCalculator `...что-то пошло не так... подобно, когда принтер умеет составлять бухгалтерские отчеты, которые потом и печатает

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +        {
в этотм метод копипаст замечен

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +            Points.Add(point);
Это слишком не имеет смысла - для метода `Add `у листа создавать метод обертку

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/SquareCalculator.cs
> +        public void CalculatedLandSquare(IList<Point> points, Logger logger)
СCalculateLandSquare (без D). метод звучит как "СделайЧтоТо", а не "СделалЧтоТо"

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +        public void TypeCoordinates(Logger logger)
Метод называется "НапечатайКоординаты", а в конце метода он уже и посчитал площадь. Хорошо, что зарплату никому не выдал за проведенные работы :)

2019-01-31 20:07 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +            return Points;
gсуровый метод....
сделай так 
`public IList<Point> Points { get; }= new List<Point>();`
Хотя непонятно зачем тебе єтот список...что если ты 5 раз вызовешь в программ все, что у тебя происходит - ты будешь точки накапливать

2019-02-01 08:02 UTC, watchbot23 commented on GDM.HW7/Services/InputCoordinates.cs
> +            return Points;
мне он нужен, чтобы потом подсчитать площадь. Нужно в метод его засунуть, но он в другом классе. Вот я и беру именно этот лист, и засовую его с помощью этого метода в калькулятор

2019-02-01 18:44 UTC, LiDmYr reviewed
1) Если честно мне вообше этот класс InputCoordinates.cs не нравится - странный контекст + странные методы , в которых ты работаешь в консолью. Надо подумать и прорефакторить код
2) в целом молодец :) задача почти выполнена.

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/SquareCalculator.cs
> +            if (resX == resY && resX != 0 && points.Count > 2)
зачем вообще проводить расчеты для `resX  `+ `resY  `если это `points.Count > 2` условие просто выбрасываент результаты  в урну?

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/FileStorage.cs
> +        Buffer Buffer = new Buffer();
добавить модификатор доступа

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/InputCoordinates.cs
> +            return Points;
вообще не понял зачем тебе метод....

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/Buffer.cs
> +        List<String> Buff = new List<string>();
модификатор доступа

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/Buffer.cs
> +            return Buff;
вот прямо что-то пошло не так - зачем мы второй раз метод делаешь ,если можешь сделать проперти лист + геттер ему дать

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/Buffer.cs
> +            if (Buff.Count != 5)
я бы писал `Buff.Count <= 5`

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/FileStorage.cs
> +            Buffer.AddMessageToBuffer(logRecord);
Почему буфер только у ФайлСтореджа...а если еще десяток каких-то IStorage прикрутить там буфера не будет?

2019-02-01 18:44 UTC, LiDmYr commented on GDM.HW7/Services/FileStorage.cs
> +            if (Buffer.GetBuffer().Count == 5)
я бы предпочел такое условие if (Buffer.Count >= 5)

2019-02-06 16:32 UTC, merged